apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-task-role
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  # Añadimos "patch" a la lista de permisos
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-task-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo
roleRef:
  kind: Role
  name: workflow-task-role
  apiGroup: rbac.authorization.k8s.io