apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  config: |
    # Y dentro de "config", especificamos el artifactRepository por defecto
    artifactRepository:
      s3:
        endpoint: minio.minio-dev.svc:9000
        bucket: argo-artifacts
        insecure: true
        accessKeySecret:
          name: minio-creds
          key: accessKey
        secretKeySecret:
          name: minio-creds
          key: secretKey